dist: trusty
sudo: false
language: java

before_cache:
  - find $HOME/.m2/repository/ -name *SNAPSHOT | xargs rm -Rf

cache:
  timeout: 1000
  directories:
    - "$HOME/.m2"

script: mvn clean install --quiet -B -Dmaven.artifact.threads=64 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

install: /bin/true

jdk:
  - openjdk7

branches:
  only:
    - master
